# Dockerfile-frontend for frontend
FROM node:22-alpine AS base
WORKDIR /app/frontend
COPY package.json package-lock.json .
RUN npm install
COPY . .

FROM node:22-alpine AS builder
WORKDIR /app/frontend
COPY --from=base /app/frontend .
RUN npm run build

FROM node:22-alpine AS final
WORKDIR /app/frontend
COPY --from=base /app/frontend/node_modules ./node_modules
COPY --from=base /app/frontend/package.json ./package.json
COPY . .
COPY --from=builder /app/frontend/dist ./dist
EXPOSE 8000
ENTRYPOINT ["npm", "run", "dev"]