# Dockerfile-node for backend
FROM node:22-alpine
WORKDIR /app/backend
COPY backend/package.json .
RUN npm install --production
COPY backend . .
COPY frontend /app/frontend

USER root
CMD ["node", "src/index.js"]
